<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MarketTest\SampleTest'                => __DIR__ . '/tests/Market/SampleTest.php',
    'MarketTest\Framework\TestCase'        => __DIR__ . '/tests/Market/Framework/TestCase.php',
    'Market\Module'                        => __DIR__ . '/Module.php',
    'Market\Controller\IndexController'    => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Controller\ViewController'     => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\PostController'     => __DIR__ . '/src/Market/Controller/PostController.php',
    'Market\Factory\PostControllerFactory' => __DIR__ . '/src/Market/Factory/PostControllerFactory.php',
    'Market\Factory\PostFormFactory'       => __DIR__ . '/src/Market/Factory/PostFormFactory.php',
    'Market\Factory\PostFilterFactory'     => __DIR__ . '/src/Market/Factory/PostFilterFactory.php',
    'Market\Form\PostFilter'               => __DIR__ . '/src/Market/Form/PostFilter.php',
    'Market\Form\PostForm'                 => __DIR__ . '/src/Market/Form/PostForm.php',
);
